apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-southeast-1

vpc:
  id: vpc-09ee0ce943b8c8d63
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-southeast-1a:
        id: subnet-
      ap-southeast-1b:
        id: subnet-
    private:
      ap-southeast-1a:
        id: subnet-
      ap-southeast-1b:
        id: subnet-

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true